import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })
const plus_Jakarta_Sans = Plus_Jakarta_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Advanced Parking',
	description: 'Generated by Advanced Parking'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={plus_Jakarta_Sans.className}>
				<Navbar />
				{children}
				<div className='text-md bg-erieblack text-ghostwhite font-medium sm:text-md text-center text-xl'>
					<p className=''>Advanced Parking &copy; 2024. All Rights Reserved.</p>
				</div>
			</body>
		</html>
	)
}
